platform :ios, '10.0'

target 'LMLoading' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for LMLoading
  pod 'SwiftLint'
  pod 'lottie-ios'

  target 'LMIntegrationTests' do
    inherit! :complete
    # Pods for LMIntegrationTests
    pod 'KIF'
  end
end
