# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do

  # -----------------------
  # before all lanes
  # -----------------------
  before_all do |lane|
    sh("if [ -d ../reports ]; then rm -Rf ../reports; fi")
    sh("if [ -f *.xml ]; then rm -f *.xml; fi")
  end

  # -----------------------
  # lanes
  # -----------------------
  lane :tests do
    scan(
      xcargs: "ONLY_ACTIVE_ARCH=YES",
      scheme: "LMLoading",
      project: "Framework/LMLoading.xcodeproj",
      code_coverage: true,
      output_directory: "reports",
      fail_build: false,
      suppress_xcode_output: false,
      configuration: "Debug"
    )
  end

  lane :build do
    tests
  end
end
